<<<<<<< HEAD


services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - ./nodered-data:/data
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - mynetwork

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin         
      # RabbitMQ connection settings
      - KK_TO_RMQ_URL=rabbitmq
      - KK_TO_RMQ_PORT=5672
      - KK_TO_RMQ_VHOST=/
      - KK_TO_RMQ_USERNAME=guest
      - KK_TO_RMQ_PASSWORD=guest
      - KK_TO_RMQ_USE_TLS=false
      - KK_TO_RMQ_EXCHANGE =amq.topic
      - KK_TO_RMQ_KEY_STORE =
      - KK_TO_RMQ_KEY_STORE_PAS=
      - KK_TO_RMQ_TRUST_STORE=
      - KK_TO_RMQ_TRUST_STORE_PASS=
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/providers:/opt/keycloak/providers
    command: 
      - start-dev
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  node-red-data:
  minio-data:
  
  
=======
services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - ./nodered-data:/data
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    ports:
      - "8080:8080"
    command: 
      - start-dev
    networks:
      - mynetwork


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  node-red-data:
  minio-data:
>>>>>>> 893f0dfad5b9a897a23562186ec4612b08f623c5
