
services:
  # Node-RED service
  node-red:
    image: nodered/node-red:latest  # Using the official Node-RED image
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - ./nodered-data:/data  # Bind mount for persisting Node-RED flows
    networks:
      - mynetwork  # Custom network

  # MinIO service

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:management  # Using the official RabbitMQ image with management plugin
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ AMQP port
      - "15672:15672"  # RabbitMQ Management Console
    networks:
      - mynetwork  # Custom network

  
networks:
  mynetwork:
    driver: bridge

volumes:
  node-red-data:  # Bind mount for Node-RED data (created locally)
  minio-data:     # Bind mount for MinIO data (created locally)
