
services:
  
  node-red:
    image: nodered/node-red:latest  
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - ./nodered-data:/data  
    networks:
      - mynetwork  




  rabbitmq:
    image: rabbitmq:management  
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"  
    networks:
      - mynetwork  

  
networks:
  mynetwork:
    driver: bridge

volumes:
  node-red-data:  
  minio-data:     
