apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
  - name: s3-api
    port: 9000
    targetPort: 9000
  - name: web-console
    port: 9001
    targetPort: 9001
  type: NodePort  # Exposes MinIO externally